[package]
name = "opengl"
version = "0.1.0"
authors = ["Gulshan Singh <gsingh2011@gmail.com>"]

[dependencies]
env_logger = "*"
freetype-rs = "*"
genmesh = "*"
glium = "*"
image = "*"
log = "*"
nalgebra = "*"
obj = "*"
time = "*"
